export const Users= [
    {
        id:1,
        profilePicture:"posts/post 1.jpg",
        username:"Snehal Kanase",
    },
    {
        id:2,
        profilePicture:"posts/post 2.jpg",
        username:"Shubham Kanase",
    },
    {
        id:3,
        profilePicture:"posts/post 3.jpg",
        username:"Aparna Sawant",
    },
    {
        id:4,
        profilePicture:"posts/post 4.jpg",
        username:"Divya More",
    },{
        id:5,
        profilePicture:"posts/post 5.jpg",
        username:"Sapna kanase",
    },{
        id:6,
        profilePicture:"posts/post 6.jpg",
        username:"Nidhish",
    },{
        id:7,
        profilePicture:"posts/post 1.jpg",
        username:"Prachi",
    },{
        id:8,
        profilePicture:"posts/post 1.jpg",
        username:"Vivek Sawant",
    },{
        id:9,
        profilePicture:"posts/post 1.jpg",
        username:"Dipti Raut",
    },{
        id:10,
        profilePicture:"posts/post 1.jpg",
        username:"Mandar Y",
    },

];

export const Posts =[
    {
        id:1,
        desc :" hello Friends",
        img:"posts/post 1.jpg",
        date:"5 min ago",
        price:"9004",
        userId:1,
        likes: 32,
        comments:9,
    },
    {
        id:2,
        desc :" hello ",
        img:"posts/post 2.jpg",
        date:"25 min ago",
        price:"3000",
        userId:2,
        likes: 322,
        comments:29,
    },
    {
        id:3,
        desc :" hello Friends",
        img:"posts/post 3.jpg",
        date:"53 min ago",
        price:"3448",
        userId:3,
        likes: 33,
        comments:39,
    },
    {
        id:4,
        desc :"",
        img:"posts/post 4.jpg",
        date:"1 hour ago",
        price:"7444",
        userId:4,
        likes: 342,
        comments:49,
    },
    {
        id:5,
        desc :" hello Friends",
        img:"posts/post 5.jpg",
        price:"1564",
        date:"5 min ago",
        userId:5,
        likes: 352,
        comments:59,
    },
    {
        id:6,
        desc :" hello Friends",
        img:"posts/post 6.jpg",
        date:"6 min ago",
        price:"1444",
        userId:6,
        likes: 32,
        comments:9,
    },
    {
        id:7,
        desc :" hello Friends",
        img:"posts/post 7.jpg",
        date:"5 min ago",
        price:"944",
        userId:7,
        likes: 32,
        comments:9,
    },
    {
        id:8,
        desc :" hello Friends",
        img:"posts/post 8.jpg",
        date:"58 min ago",
        price:"3894",
        userId:8,
        likes: 32,
        comments:9,
    },
    {
        id:9,
        desc :" hello Friends",
        img:"posts/post 9.jpg",
        date:"5 min ago",
        price:"2444",
        userId:9,
        likes: 32,
        comments:9,
    },
    {
        id:10,
        desc :" hello Friends",
        img:"posts/post 10.jpg",
        date:"5 min ago",
        userId:10,
        price:"6555",
        likes: 32,
        comments:9,
    },
]